### ISSUE TITLE
Following instructions but app will not run

### ISSUE THREAD

**Issue by gordon-frobenius-psa** [coldbox-templates/rest#10]
I am following your [Building REST APIs](https://coldbox.ortusbooks.com/digging-deeper/recipes/building-rest-apis) tutorial but I am not getting the results that tutorial is saying I should.  Here are the differences I'm seeing...

* `{class="coldbox.system.interceptors.SES"}` is not present in my `Coldbox.cfc->interceptors`.  So I added it.
* In the "Defining URL Routes" section it says *"Let's add the following new routes to our /config/routes.cfm file BEFORE the default route."*.  Problem is, there is not `routes.cfm` in the config folder.  There is a `router.cfc`.  So I put the two "addRoute()" examples in it (not sure if this is correct).
* Then when I try to access http://127.0.0.1:59685/api/user/123 I get this error:

> Event: api.user.view 
> Routed URL: api/user/123/ 
> Layout: Main.cfm (Module: ) 
> View: api/user/view 
> Timestamp: 04/16/2019 05:09:59 PM
> Type: MissingInclude 
> Messages: Could not find the included template //layouts/Main.cfm.

There are no layouts in this skeleton so I'm confused as to why it's trying to call one.  I know this is probably all very basic stuff.  I've only been playing around with Coldbox for a few days.  I'd like to get a REST skeleton app working so I can start learning more about it.  My company is very intrigued by your products, especially Testbox.  If I can get some basic stuff up and running I can see them paying for some on-site support.  Thank you!

**Comment by lmajano** [comment]
It seems we need to update that recipe to coldbox 5. I will take care of it. If you want. Start with the 60 minute guide. https://coldbox.ortusbooks.com/for-newbies/60-minute-quick-start

**Comment by lmajano** [comment]
I have completely rewritten the guide to support ColdBox 5.  Please check it out
https://coldbox.ortusbooks.com/digging-deeper/recipes/building-rest-apis
