### ISSUE TITLE
Should "can handle missing actions" test expect 404 instead of 405?

### ISSUE THREAD

**Issue by sethstone** [coldbox-templates/rest#17]
In this test we are expecting a call to "echo/bogus" to return a 405 (method not allowed), but this expectation is failing for me by default because I'm getting back a 404 status code:

https://github.com/coldbox-templates/rest/blob/51454f9a87849f014dc60cc095674fdaa8f1c91d/tests/specs/integration/EchoTests.cfc#L76-L82

404 seems like it would be the correct status code so I just wanted to clarify what the expected result should be.

**Comment by lmajano** [comment]
I think so @sethstone . I think the default for bad routes now is 404's
